name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of code
        uses: actions/checkout@v4.1.7
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push of the image
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            takahashidt/review-filmes:v${{ github.run_number }}
            takahashidt/review-filmes:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout of code
        uses: actions/checkout@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: config of kubeconfig
        run: aws eks update-kubeconfig --name aula-eks
      - name: Deploy no kubernetes
        uses: Azure/k8s-deploy@v5
        with:
           manifests: |
              ./k8s/deployment.yaml
           images: |
             takahashidt/review-filmes:v${{ github.run_number }}
